"""add daily challenge

Revision ID: 9c763efd6580
Revises: e84245140232
Create Date: 2026-09-12 01:31:04.536674

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '9c763efd6580'
down_revision: Union[str, Sequence[str], None] = 'e84245140232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
