"""add achievement conditions

Revision ID: e84245140232
Revises: a2c4e6b8d1f3
Create Date: 2026-09-12 01:22:27.754261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84245140232'
down_revision: Union[str, Sequence[str], None] = 'a2c4e6b8d1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('streak', 'last_activity',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_unique_constraint('uq_streak_user', 'streak', ['user_id'])
    op.create_unique_constraint('uq_user_achievement_user_achievement', 'user_achievement', ['user_id', 'achievement_id'])
    op.create_unique_constraint('uq_user_progress_user_lesson', 'user_progress', ['user_id', 'lesson_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_progress_user_lesson', 'user_progress', type_='unique')
    op.drop_constraint('uq_user_achievement_user_achievement', 'user_achievement', type_='unique')
    op.drop_constraint('uq_streak_user', 'streak', type_='unique')
    op.alter_column('streak', 'last_activity',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
